### ISSUE TITLE
Not able to infer_trajectory using any model with dynverse, Error in match.argError in match.arg(backend, choices = c("docker", "singularity")) :    'arg' should be one of “docker”, “singularity”

### ISSUE THREAD

**Issue by ammarsabir15** [dynverse/dyno#110]
Hi, 

I am trying to use dynverse for trajectory inference but I am not able to do so, the code works fine but as soon as I give the command to `infer_trajectory` then it gives an error as given below,

```
library(dyno)
library(tidyverse) 
data("fibroblast_reprogramming_treutlein")

dataset <- wrap_expression(
  counts = fibroblast_reprogramming_treutlein$counts,
  expression = fibroblast_reprogramming_treutlein$expression
)

guidelines <- guidelines_shiny(dataset)
methods_selected <- guidelines$methods_selected

is_wrapper_with_prior_information(dataset)

answers <- dynguidelines::answer_questions(
  multiple_disconnected = NULL, 
  expect_topology = NULL, 
  expected_topology = NULL, 
  n_cells = 392, 
  n_features = 2000, 
  memory = "60GB", 
  docker = FALSE
)
guidelines <- dynguidelines::guidelines(answers = answers) 
methods_selected <- guidelines$methods_selected


model <- infer_trajectory(dataset, first(methods_selected))
Error in match.arg(backend, choices = c("docker", "singularity")) : 
  'arg' should be one of “docker”, “singularity”
```

I have tried to solve this problem but I did not find where this `match.arg` function is present, is there a way to solve this problem?

Thanks,
Ammar

**Comment by KforKuma** [comment]
I had this question and fixed it via installing singularity or docker.

**Comment by Woqo** [comment]
Yes, this package needs Docker Container.
You should install docker firstly.

##my system is Windows 10

**Comment by rcannood** [comment]
@ammarsabircheema thanks for reporting this issue, @KforKuma for finding the solution, and @Woqo for confirming that it works! 

I'm updating babelwhale to print a more useful error message in case neither docker or singularity are installed.
