### ISSUE TITLE
Error when using plot_dimred

### ISSUE THREAD

**Issue by CromitDolores0808** [dynverse/dyno#113]
Here is my code:
plot_dimred(
  model
)
The model was built successfully. 
Here is the error:

Coloring by milestone
Using milestone_percentages from trajectory
Error: Must supply a symbol or a string as argument
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/rlang_error>
Must supply a symbol or a string as argument
Backtrace:
  1. patchwork::wrap_plots(...)
 10. tidyr:::gather.data.frame(...)
 13. tidyr:::ensym2(key)
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/rlang_error>
Must supply a symbol or a string as argument
Backtrace:
     █
  1. ├─patchwork::wrap_plots(...)
  2. │ └─patchwork:::is_valid_plot(..1)
  3. │   └─ggplot2::is.ggplot(x)
  4. ├─dynplot::plot_dimred(model)
  5. │ └─dynplot:::project_waypoints_coloured(...)
  6. │   └─`%>%`(...)
  7. ├─dplyr::summarise(...)
  8. ├─dplyr::group_by(., .data$from, .data$to, .data$comp_name)
  9. ├─tidyr::gather(., .data$comp_name, .data$comp_value, starts_with("comp_"))
 10. └─tidyr:::gather.data.frame(...)
 11.   ├─rlang::as_string(ensym2(key))
 12.   │ └─rlang::is_string(x)
 13.   └─tidyr:::ensym2(key)

R version 3.6.1

Many thanks!

**Comment by TJonCooper** [comment]
I'm also experiencing this error:

https://github.com/dynverse/dyno/issues/112

**Comment by TJonCooper** [comment]
Please update to the latest, developmental version of dyno or dynplot - and this error should be fixed AFAIK:

`devtools::install_github("dynverse/dynplot@devel")`

**Comment by CromitDolores0808** [comment]
> Please update to the latest, developmental version of dyno or dynplot - and this error should be fixed AFAIK:
> 
> `devtools::install_github("dynverse/dynplot@devel")`

Thanks! But here is another error after reinstalling the dynplot@devel and dyno@devel  :
> plot_dimred(model)
Coloring by milestone
Using milestone_percentages from trajectory
Error: Problem with `summarise()` input `color`.
x lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/dynplot/R/dynplot.rdb' is corrupt
ℹ Input `color` is `mix_colors(.data$milestone_id, .data$percentage, milestone_colors)`.
ℹ The error occurred in group 1: cell_id = "P1_P_AACAAAGTCCATAAGC".
Run `rlang::last_error()` to see where the error occurred.
In addition: Warning messages:
1: In .Call(dplyr_mask_eval_all_summarise, quo, private) :
  restarting interrupted promise evaluation
2: In mask$eval_all_summarise(quo) : internal error -3 in R_decompress1

**Comment by rcannood** [comment]
Thanks @TJonCooper bringing this up. In the meantime, this version of dynplot has been published to CRAN, so simply updating dynplot should also do the trick.

@CromitDolores0808 Could you try restarting R before updating dynplot?

**Comment by CromitDolores0808** [comment]
> Thanks @TJonCooper bringing this up. In the meantime, this version of dynplot has been published to CRAN, so simply updating dynplot should also do the trick.
> 
> @CromitDolores0808 Could you try restarting R before updating dynplot?

Many Thanks! It works.

**Comment by wfma** [comment]
I just had the same issues running slingshot. The model run took several hours and plot_dimred produced the exact same error code.

I just restarted R and updated to developmental version via devtools::install_github("dynverse/dynplot@devel")

and the error resolved.
