### ISSUE TITLE
Cannot open connection 

### ISSUE THREAD

**Issue by laols574** [dynverse/dyno#16]
when executing guidelines <- guidelines_shiny(task) I get the error: 
Error in file(con, "r") : 
  cannot open the connection to 'https://www.googletagmanager.com/gtag/js?id = UA-578149-3'
In addition: Warning message:
In file(con, "r") :

This website successfully opens when I type it into a browser so I'm at a loss for why it cannot open in R. Is this an error other users have encountered?

**Comment by zouter** [comment]
Hi!
Thank you for trying out the package. This was a tiny typo, now fixed in dynverse/dynguidelines#4

Thanks
Wouter
