### ISSUE TITLE
static port for shiny app

### ISSUE THREAD

**Issue by vibbits** [dynverse/dyno#19]
Hi, I am experimenting with a docker-base setup of training sessions. Given that your package has been shown in our latest course, it tried to get the [script](http://data.bits.vib.be/pub/trainingen/summer/analysisDyno.R) running in a Jupyter notebook environment.
Installation in the docker goes fine but I have the idea that the port the shiny app is opened on e.g. 127.0.0.1:3880 varies each time. Would it be possible to use a static port? 
Thanks for your feedback.

BTW: I am happy to explain more of the background via email if needed. It is still test phase and technology scouting.

**Comment by zouter** [comment]
Hi!
Thanks for trying out the dyno workflow!
Fixing the port can be done in two ways (which were not yet documented):

- Using options: `options(shiny.port = XXX)`
- If you update dynguidelines using `devtools::install_github("dynverse/dynguidelines")` there is now an extra parameter: `guidelines_shiny(..., port = XXX)`

PS: At the moment we're updating the guidelines based on new results from the benchmarking, so the top methods will almost certainly change with this new update. The dyno functionality as described in your script will stay the same however.

**Comment by zouter** [comment]
Closing this for now, feel free to reopen if this is still an issue!

**Comment by ccruizm** [comment]
Good day!

I am using jupyter notebook with an R kernel. Everything works except opening the `guidelines_shiny`. I am not sure how to map the port to open the GUI in a new tab on my web browser.  have tried setting the `port` within the function but get an error:

```
Loading required package: shiny


Listening on http://0.0.0.0:8888

Error in utils::browseURL(appUrl): 'browser' must be a non-empty character string
Traceback:

1. guidelines_shiny(dataset = gbm.pseudotime, port = 8888)
2. shiny::runApp(app, port = port, launch.browser = launch.browser, 
 .     host = host, ...)
3. utils::browseURL(appUrl)
4. stop("'browser' must be a non-empty character string")
```

Do you know how I could solve this issue? sorry if it is a trivial question.

Thanks in advance
