### ISSUE TITLE
Error in eval_tidy(enquo(var), var_env) : object 'method_id' not found

### ISSUE THREAD

**Issue by ysu2015** [dynverse/dyno#23]
Hi,

I met the error message when I run the tutorial code. "Error in eval_tidy(enquo(var), var_env) : object 'method_id' not found". Could you try to help me out? Thanks a lot.

the details show in below. 
> guidelines <- guidelines_shiny(dataset)
Loading required package: shiny

Listening on http://0.0.0.0:3209
Code to reproduce the guidelines, copy it over to your script!

# Reproduces the guidelines as created in the shiny app
answers <- dynguidelines::answer_questions(
  multiple_disconnected = NULL, 
  expect_topology = NULL, 
  expected_topology = NULL, 
  n_cells = 392, 
  n_features = 2000, 
  prior_information = NULL
)
guidelines <- dynguidelines::guidelines(answers = answers) 
> 
> methods <- guidelines$methods %>% filter(selected) %>% pull(method_id) %>% first()
Error in eval_tidy(enquo(var), var_env) : object 'method_id' not found

**Comment by zouter** [comment]
Hi!
This was some old code in the readme. The correct way to get the methods is by using `methods <- guidelines$methods_selected` this is now updated in the readme

**Comment by ysu2015** [comment]
Got it. Thanks a lot.
Y
