### ISSUE TITLE
How to prepare the input dataset?

### ISSUE THREAD

**Issue by ysu2015** [dynverse/dyno#25]
Hi Zouter,
Thank you so much for your quick response and help. The tutorial runs smoothly in my hand finally.
I am trying to run some real datasets which download from GEO. Do you have some pieces of instruction on how to prepare the input dataset from digital expression reads, such as Drop-seq output? That would be very help. thanks a lot.

Y

**Comment by zouter** [comment]
Hi @ysu2015 

All trajectory methods start from a counts matrix, or from normalised expression matrix (which can be TPM, log2, etc...). 

So the answer to your question depends on how much of the processed data is available:

* Usually the authors already provide a count or normalized count matrix. For single-cell data this is usually as supplementary files at the bottom of the GEO page. For example: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE60781 , you would need the GSE60781_RPKM.txt.gz file

* When this is not available, you will have to process the data from the reads. At the moment, I would suggest this workflow: https://github.com/Hoohm/dropSeqPipe It's relatively easy to install (https://github.com/Hoohm/dropSeqPipe/wiki/Installation) and contains all the steps starting from the reads to the expression matrix.

Wouter

**Comment by zouter** [comment]
Closing this for now, but feel free to open a new issue.
