### ISSUE TITLE
Error during trajectory inference: unused argument (env = processx_env)

### ISSUE THREAD

**Issue by squirrelandr** [dynverse/dyno#29]
I am following the dyno demo (https://github.com/dynverse/dyno#installation) and run into error at the following step.  Prior to this step, because the "guidelines <- guidelines_shiny(dataset)" doesn't work, so I manually set the value of "methods_selected" to "scorpius".

> model <- infer_trajectory(dataset, first(methods_selected))
Error traceback:
2: unused argument (env = processx_env)
1: processx::run
   processx_command
   processx_args
   processx_env
   verbose
   verbose
   TRUE
   FALSE
Error: Error during trajectory inference 
unused argument (env = processx_env)

**Comment by squirrelandr** [comment]
Thank you Zouter, installing processx version 3.2.0 solves the problem.

Stepping forward, I ran into another error (I am on R3.4.4):

> plot_dimred(model, expression_source = dataset$expression, grouping = fibroblast_reprogramming_treutlein$grouping)
Error in filter_impl(.data, quo) : 
  Evaluation error: argument "x" is missing, with no default.
>

**Comment by zouter** [comment]
Hi @squirrelandr 

Sorry for not getting back to you. A lot has changed to dyno since you got this error. Are you still having problems with this if you reinstall it now?

Thanks
Wouter

**Comment by rcannood** [comment]
This problem should have been fixed, closing this issue.
