### ISSUE TITLE
Error: Column `is_start` can't be converted from integer to logical

### ISSUE THREAD

**Issue by Eomesodermin** [dynverse/dyno#49]
Hi, 

I keep getting an error when trying to plot the trajectory on a dim reduction using plot_dimred() function. 

below is an example of analysis flow:

raw.data.spleen <- read.table("output/tables/raw_dataframe_Spleen_only.txt")
normed.data.spleen <- read.table("output/tables/filtered_dataframe_Spleen_only.txt")

Dyno.spleen.data <- wrap_expression(
  counts = raw.data.spleen,
  expression = normed.data.spleen
)

answers.spleen <- dynguidelines::answer_questions(
  multiple_disconnected = NULL, 
  expect_topology = NULL, 
  expected_topology = NULL, 
  n_cells = 3447, 
  n_features = 12236, 
  memory = "8GB", 
  prior_information = NULL, 
  docker = TRUE
)

slingshot.spleen <- infer_trajectory(Dyno.spleen.data, 
                                    method = "dynverse/ti_slingshot:v0.9.9.01", 
                                    parameters = NULL, 
                                    give_priors = NULL, 
                                    seed = set.seed(42),
                                    verbose = TRUE)

plot_dimred(slingshot.spleen)

> Coloring by milestone
> Using milestone_percentages from trajectory
> Error: Column `is_start` can't be converted from integer to logical

> traceback()
13: stop(list(message = "Column `is_start` can't be converted from integer to logical", 
        call = NULL, cppstack = NULL))
12: bind_rows_(x, .id)
11: bind_rows(divergence_regions, extra_divergences)
10: calculate_geodesic_distances_(cell_ids = trajectory$cell_ids, 
        milestone_ids = trajectory$milestone_ids, milestone_network = trajectory$milestone_network, 
        milestone_percentages = trajectory$milestone_percentages, 
        divergence_regions = trajectory$divergence_regions, waypoint_cells = waypoint_cells, 
        waypoint_milestone_percentages = waypoint_milestone_percentages)
9: calculate_geodesic_distances(trajectory, waypoint_milestone_percentages = waypoint_milestone_percentages)
8: dynwrap::select_waypoints(trajectory)
7: is.data.frame(x)
6: colnames(waypoints$geodesic_distances)
5: eval_bare(get_expr(quo), get_env(quo))
4: quasi_label(enquo(expected))
3: testthat::expect_setequal(cell_positions$cell_id, colnames(waypoints$geodesic_distances))
2: project_waypoints(trajectory = trajectory, cell_positions = cell_positions, 
       waypoints = waypoints, trajectory_projection_sd = trajectory_projection_sd, 
       color_trajectory = color_trajectory)
1: plot_dimred(slingshot.liver)

**Comment by rcannood** [comment]
Hello Eomesodermin,

Does the problem also occur when you use the most recent version of the ti_slingshot container (`"dynverse/ti_slingshot:v1.0.0.01"` or `ti_slingshot()`)? Make sure that dynwrap and dynmethods are also up to date.

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Closing this issue since it is likely already solved. Feel free to respond to this message if it is not.
