### ISSUE TITLE
Error: 'manhattan_distance' is not an exported object from 'namespace:dynutils'

### ISSUE THREAD

**Issue by elimereu** [dynverse/dyno#50]
Hi, 
thank you for this amazing package and study! I would like to use your package for my analysis, so I'm testing it. 
I get this error when I try to make the plot with the following commands:

plot_dimred(
  model, 
  expression_source = dataset$expression, 
  color_cells = "feature",
  feature_oi = "Vim",
  color_density = "grouping",
  grouping = fibroblast_reprogramming_treutlein$grouping,
  label_milestones = FALSE
)

Any help for this? Thanks!

**Comment by zouter** [comment]
Hi @elimereu 

Sorry for this, I found the solution but don't have time now to finalise the fix now. I will try to fix this tomorrow morning.

**Comment by elimereu** [comment]
Thanks!! 😊

**Comment by zouter** [comment]
Hi! This should be fixed if you do `devtools::install_github("dynverse/dynwrap@master")`

**Comment by elimereu** [comment]
Thanks a lot! All plots are now working but heatmaps. I don’t know why but when I run  
like in the tutorial the command runs and without errors but there is no plot as output. 
Any explanation for this?



Thanks, 

Elisabetta

**Comment by zouter** [comment]
This is a bug somewhere in the patchwork package. The heatmap should show if you press zoom in :wink: .

**Comment by rcannood** [comment]
Closing this issue since it has been fixed.
