### ISSUE TITLE
Error in plot_dimred function

### ISSUE THREAD

**Issue by Eomesodermin** [dynverse/dyno#51]
I keep getting this error and am unable to resolve it. 

I have tried plotting different trajectories and other arguments. 

I have also tried both the most up to date version and previous versions of dynutils and the dyno package. 

dynplot::plot_dimred(slingshot.total, color_cells = "pseudotime")
> Error: 'manhattan_distance' is not an exported object from 'namespace:dynutils'

sessionInfo()
>R version 3.5.3 (2019-03-11)
>Platform: x86_64-apple-darwin15.6.0 (64-bit)
>Running under: macOS Mojave 10.14.3

>Matrix products: default
>BLAS: >/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
>LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

>locale:
>[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

>attached base packages:
>[1] stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
 >[1] forcats_0.4.0       stringr_1.4.0       dplyr_0.8.0.1       purrr_0.3.2         readr_1.3.1         tidyr_0.8.3        
 >[7] tibble_2.1.1        tidyverse_1.2.1     dynutils_1.0.3      dyno_0.1.1          dynwrap_1.0.1       >dynplot_1.0.0.9000 
>[13] dynmethods_1.0.1    dynguidelines_1.0.0 dynfeature_1.0.0    Seurat_2.3.4        Matrix_1.2-17       >cowplot_0.9.4      
>[19] ggplot2_3.1.1      

>loaded via a namespace (and not attached):
 > [1] utf8_1.1.4            reticulate_1.12       R.utils_2.8.0         tidyselect_0.2.5      htmlwidgets_1.3       >grid_3.5.3           
 > [7] trimcluster_0.1-2.1   ranger_0.11.2         Rtsne_0.15            devtools_2.0.2        dyntoy_0.9.9          >munsell_0.5.0        
 >[13] codetools_0.2-16      ica_1.0-2             withr_2.1.2           colorspace_1.4-1      knitr_1.22            >rstudioapi_0.10      
 >[19] stats4_3.5.3          ROCR_1.0-7            robustbase_0.93-4     dtw_1.20-1            gbRd_0.4-11           >labeling_0.3         
 >[25] Rdpack_0.11-0         lars_1.2              polyclip_1.10-0       bit64_0.9-7           farver_1.1.0          >rprojroot_1.3-2      
 >[31] generics_0.0.2        xfun_0.6              diptest_0.75-7        R6_2.4.0              GA_3.2                pdist_1.2            
> [37] hdf5r_1.2.0           flexmix_2.3-15        bitops_1.0-6          assertthat_0.2.1      promises_1.0.1        SDMTools_1.1-221.1   
 >[43] scales_1.0.0          ggraph_1.0.2          nnet_7.3-12           gtable_0.3.0          babelwhale_0.0.0.9000 npsurv_0.4-0         
> [49] processx_3.3.0        tidygraph_1.1.2       rlang_0.3.4           akima_0.6-2           splines_3.5.3         lazyeval_0.2.2       
 >[55] acepack_1.4.1         hexbin_1.27.2         broom_0.5.2           checkmate_1.9.3       modelr_0.1.4          BiocManager_1.30.4   
 >[61] yaml_2.2.0            reshape2_1.4.3        backports_1.1.4       httpuv_1.5.1          Hmisc_4.2-0           tools_3.5.3          
 >[67] usethis_1.5.0         gplots_3.0.1.1        RColorBrewer_1.1-2    proxy_0.4-23          sessioninfo_1.1.1     ggridges_0.5.1       
> [73] Rcpp_1.0.1            plyr_1.8.4            base64enc_0.1-3       ps_1.3.0              prettyunits_1.0.2     rpart_4.1-15         
 >[79] pbapply_1.4-0         viridis_0.5.1         dynparam_1.0.0        zoo_1.8-5             haven_2.1.0           ggrepel_0.8.0        
 >[85] cluster_2.0.9         fs_1.3.0              magrittr_1.5          RSpectra_0.14-0       data.table_1.12.2     carrier_0.1.0        
 >[91] lmtest_0.9-37         RANN_2.6.1            mvtnorm_1.0-10        fitdistrplus_1.0-14   pkgload_1.0.2         hms_0.4.2            
 >[97] patchwork_0.0.1       lsei_1.2-0            mime_0.6              xtable_1.8-4          readxl_1.3.1          mclust_5.4.3         
>[103] gridExtra_2.3         testthat_2.1.1        compiler_3.5.3        KernSmooth_2.23-15    crayon_1.3.4          rje_1.9              
>[109] R.oo_1.22.0           htmltools_0.3.6       proxyC_0.1.3          segmented_0.5-3.0     later_0.8.0           Formula_1.2-3        
>[115] snow_0.4-3            RcppParallel_4.4.2    lubridate_1.7.4       tweenr_1.0.1          MASS_7.3-51.4         fpc_2.1-11.1         
>[121] cli_1.1.0             R.methodsS3_1.7.1     gdata_2.18.0          parallel_3.5.3        metap_1.1             igraph_1.2.4.1       
>[127] pkgconfig_2.0.2       dyneval_0.9.9         sp_1.3-1              foreign_0.8-71        xml2_1.2.0            foreach_1.4.4        
>[133] vipor_0.4.5           rvest_0.3.3           bibtex_0.4.2          callr_3.2.0           digest_0.6.18         dyndimred_1.0.1      
>[139] RcppAnnoy_0.0.11      tsne_0.1-3            cellranger_1.1.0      htmlTable_1.13.1      uwot_0.1.3            curl_3.3             
>[145] kernlab_0.9-27        shiny_1.3.2           gtools_3.8.1          modeltools_0.2-22     nlme_3.1-139          jsonlite_1.6         
>[151] fansi_0.4.0           desc_1.2.0            viridisLite_0.3.0     pillar_1.3.1          lattice_0.20-38       shades_1.3.1         
>[157] httr_1.4.0            DEoptimR_1.0-8        pkgbuild_1.0.3        survival_2.44-1.1     glue_1.3.1            remotes_2.0.4        
>[163] FNN_1.1.3             png_0.1-7             prabclus_2.2-7        iterators_1.0.10      bit_1.1-14            ggforce_0.2.2        
>[169] class_7.3-15          stringi_1.4.3         mixtools_1.1.0        doSNOW_1.0.16         latticeExtra_0.6-28   caTools_1.17.1.2     
>[175] memoise_1.1.0         irlba_2.3.3           ape_5.3

**Comment by rcannood** [comment]
Hello Eomesodermin,

Most likely you have an outdated version of dynplot installed. Could you try updating dynplot? (`devtools::install_github("dynverse/dynplot")`)

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Closing this issue since it is probably already fixed. Feel free to respond if it is not.
