### ISSUE TITLE
Question: SCE to H5AD

### ISSUE THREAD

**Issue by friedue** [dynverse/dyno#58]
Hi,
this is just a question, not really an issue -- I was just wondering whether you could point me to a function that would enable me to convert my SingleCellExperiment objects into scanpy-ready H5AD objects?

Cheers,

Friederike

**Comment by rcannood** [comment]
Hi Friederike!

I would love to help you, but wouldn't it make more sense to ask this question to the maintainers of SingleCellExperiment or scanpy?

Kind regards,
Robrecht

**Comment by friedue** [comment]
I have asked them :)

I just thought you'd have a solution implemented anyway (or at least some code I could look at) -- maybe I should rephrase: How does dynverse handle the conversion between SCE and AnnData?

**Comment by rcannood** [comment]
We don't, actually. [dyncli](https://github.com/dynverse/dyncli/blob/master/R/parse_dataset.R) has a bit of code to read expression matrices from loom files, cellranger files, and our h5 file formats, but doesn't support SCE or scanpy. 

If anybody has a lot of time on their hands, it would be interesting to have a converter between all of these formats, although some aspects of the formats are inherently incompatible between each other.

**Comment by friedue** [comment]
Ah, I thought you allowed users to run PAGA etc., which I just assumed needed some type of conversion.

**Comment by rcannood** [comment]
No, not really :) We use dyncli to write the data from an R session to our own custom hdf5 format. It then gets read by [dyncli](https://github.com/dynverse/ti_monocle_ddrtree/blob/master/run.R#L3) (for R) or [dynclipy](https://github.com/dynverse/ti_paga/blob/master/run.py#L3-L4) (for Python) in order to get all of the data inside the R / python script.

If you need to transfer data from R to python, you _could_ use dyncli to do it.

**Comment by friedue** [comment]
Ah, I see. What are the main differences between your HDF5 format and the "proper" scanpy one?

**Comment by rcannood** [comment]
A H5 format is basically a directory structure. Scanpy uses a totally different one from what the dynverse packages use. 

I'm going to close this issue, as it is not related to any of the dynverse packages :)
