### ISSUE TITLE
Problem with singularity/docker?

### ISSUE THREAD

**Issue by ltosti** [dynverse/dyno#63]
Hi there,

I installed the package as recommended and I opted for singularity. When I run ```dynwrap::test_singularity_installation(detailed = TRUE)```, I get 

```
✔ Singularity is installed
✔ Singularity is at correct version (>=3.0): 3.3.0-1 is installed
✔ Singularity can pull and run a container from Dockerhub
✔ Singularity can mount temporary volumes
✔ Singularity test successful ------------------------------------------------------------
[1] TRUE
```

However, when I run ```model <- infer_trajectory(dataset, ti_comp1())``` as in the user guide I get now the following error 

```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/version: dial unix /var/run/docker.sock: connect: permission denied
Error in processx::run("docker", c("images", paste0("--format=", format),  : 
  System command error
```

Any idea of what's happening?

**Comment by zouter** [comment]
Hi!

Most probably it's still trying to run docker, because it detects that it is installed. You can set the default container environment using `babelwhale::set_default_config(create_singularity_config())`.

Hope that helps :slightly_smiling_face:

**Comment by rlorenzc** [comment]
Hi!

I'm also actually trying to run this as well. When I do run:
`babelwhale::set_default_config(create_singularity_config()).`

I get an error:
`Error in save(config, file = config_file, compress = "gz") : 'compress = "gz"' is invalid`

Should this be "gzip" instead of "gz" like in the R base::save function?

**Comment by ltosti** [comment]
I had the same problem as @rlorenzc but we solved it by using 
```dynwrap::set_default_config(dynwrap::create_singularity_config(cache_dir = ""),permanent = FALSE)```

Hope this helps!

**Comment by whatever60** [comment]
@ltosti 

> Hi!
> 
> Most probably it's still trying to run docker, because it detects that it is installed. You can set the default container environment using `babelwhale::set_default_config(create_singularity_config())`.
> 
> Hope that helps 🙂

This should be put into a conspicuous place in the documentation.

**Comment by XMUwsa** [comment]
Hi there,

I installed the package as recommended and I opted for Docker. When I run dynwrap::test_docker_installation(detailed = TRUE), I get
`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied`
and
`Error in dynwrap::test_docker_installation(detailed = TRUE) : `
Hope for helps @zouter

**Comment by feanaros** [comment]
Same of @XMUwsa please help
