### ISSUE TITLE
authentication error running singularity?

### ISSUE THREAD

**Issue by dpschreiner** [dynverse/dyno#67]
this worked for a me a couple weeks ago on our cluster but not any more:

```
$ singularity exec 'docker://dynverse/ti_slingshot:v1.0.3' echo hi
FATAL:   Unable to handle docker://dynverse/ti_slingshot:v1.0.3 uri: failed to get SHA of 
docker://dynverse/ti_slingshot:v1.0.3: error getting username and password: error reading 
JSON file "/run/user/68333/containers/auth.json": error unmarshaling JSON at "/run/user
/68333/containers/auth.json": unexpected end of JSON input
```

**Comment by rcannood** [comment]
That's really strange. It works for me. Do you have the same problem with other containers? (e.g. ti_paga)

**Comment by dpschreiner** [comment]
yes, i have the problem with others as well. paga was in fact the one i was trying to get initially; i went back to slingshot because i was able to run that one successfully a few weeks ago.

i have filed an issue with the cluster folks here...  thanks for the reply!

**Comment by dpschreiner** [comment]
i believe this is because i had an existing session that was attempting to use singularity
