### ISSUE TITLE
singularity run image from singularity hub

### ISSUE THREAD

**Issue by seqyuan** [dynverse/dyno#74]
since I have  succed `singularity pull shub://dynverse/ti_slingshot:latest`, but when I run  `model <- infer_trajectory(dataset, "slingshot")`, it showed me `Running singularity exec 'docker://dynverse/ti_slingshot:v1.0.3' echo hi`.

what should I do to set singularity run image from `shub://dynverse/`

**Comment by zouter** [comment]
We are no longer using the singularity images from singularity hub as these are outdated (and singularity hub might cease to exist one day). The images from dockerhub are the latest version, and the `singularity exec 'docker://dynverse/ti_slingshot:v1.0.3' echo hi` command will create the latest singularity image from the docker image.

Why is it necessary for you to run the method using singularity hub?

**Comment by rcannood** [comment]
Closing this issue. Feel free to reply if further input is needed.
