### ISSUE TITLE
ti_scorpius

### ISSUE THREAD

**Issue by subkhankul** [dynverse/dyno#79]
Hi there, 
I wonder if it is possible to specify start_id and end_id in 

 model <- infer_trajectory(dataset, "scorpius", give_priors = c("start_id", "end_id"))?

I need a linear trajectory from start to end cell(s), however I can't change the trajectory no matter I add as a starting/ending points: it does not come to my "end" "H16" cluster.

![Rplot](https://user-images.githubusercontent.com/22098957/77086186-57db8980-69f9-11ea-8769-4c7b7730c5f2.jpeg)

**Comment by rcannood** [comment]
Hello @subkhankul,

SCORPIUS does not make use of any priors, and as such is invariant to your inputs. The predicted output looks quite nice, aside from H16 not being at the very end of the trajectory. You could try setting `ndim = 2`, maybe this will resolve your issue.

Alternatively, you could try slingshot instead. It is similar to SCORPIUS and does allow specifying an `end_id` cell.

Do either of these approaches provide you with a good solution?

Kind regards,
Robrecht

**Comment by rcannood** [comment]
Closing this issue. Feel free to reply if further input is needed.
