### ISSUE TITLE
No return model 

### ISSUE THREAD

**Issue by ateissan** [dynverse/dyno#83]
Hello, 

I am trying to run dynverse with singularity but nothing is stored in the object after infer_trajectory function. Do I need to set up a specific parameter?

Thanks for your help,
Aurélie

**Comment by ateissan** [comment]
Singularity seems to work fine : 


> dynwrap::test_singularity_installation(detailed = TRUE)
✔ Singularity is installed
✔ Singularity is at correct version (>=3.0): 3.5.2 is installed
✔ Singularity can pull and run a container from Dockerhub
✔ Singularity can mount temporary volumes
✔ Singularity test successful ------------------------------------------------------------
[1] TRUE

**Comment by zouter** [comment]
Hi @ateissan 

Could you try to run it with `verbose = TRUE` and provide us with the output? Thanks!

**Comment by ateissan** [comment]
Thank you for this comment. The hdf5r package was not installed. Now it's working
