### ISSUE TITLE
Error Message: "Warning: Error in : Column `start_n` not found   128: <Anonymous>"

### ISSUE THREAD

**Issue by svoter** [dynverse/dyno#9]
Hello, 
I tried running the following code from your tutorial:

library(dyno)
library(tidyverse)
data("fibroblast_reprogramming_treutlein")
dim(fibroblast_reprogramming_treutlein$expression)
task <- wrap_expression(
  counts = fibroblast_reprogramming_treutlein$counts,
  expression = fibroblast_reprogramming_treutlein$expression)
guidelines <- guidelines_shiny(task)

The shiny app will launch, but when I try clicking the "Use Methods" button, I get the following error message: "Warning: Error in : Column `start_n` not found   128: <Anonymous>" and then the window closes.  

Do you have any suggestions?

Thank you,
Sarah

**Comment by zouter** [comment]
Hi, thanks for trying out the package!

I found the probable cause of the error, and tried to fix it in dynverse/dynguidelines#1. Could you try reinstalling the package `devtools::install_github("dynverse/dynguidelines")` and see if the error is still there?

Wouter

**Comment by svoter** [comment]
It's working now! Thanks for the quick response

**Comment by ysu2015** [comment]
Hi zouter,
when I run the commands in the tutorial, I got another error.
library(dyno)
library(tidyverse)
data("fibroblast_reprogramming_treutlein")
dim(fibroblast_reprogramming_treutlein$expression)
task <- wrap_expression(
counts = fibroblast_reprogramming_treutlein$counts,
expression = fibroblast_reprogramming_treutlein$expression)
guidelines <- guidelines_shiny(task)

Error in setdiff(names(questions), given_question_ids) : 
  object 'questions' not found

**Comment by rcannood** [comment]
Hi @ysu2015,

I moved your question to a separate issue, to make sure we don't lose track of it. Check #21 for updates.

Robrecht
