### ISSUE TITLE
Is there a list of the newest version of each TI method?

### ISSUE THREAD

**Issue by wendelljpereira** [dynverse/dyno#93]
Hello,

Thank you very much for developing all the packages that are part of dynverse. It is a great tool!  

I am trying to use some different models in my dataset. I started with slingshot and realize it was an older version. Then, I noticed the issue #91 and learned how to update this model to v.2:

> create_ti_method_container("dynverse/ti_slingshot:v2.0.1")

How do I know if the version of a module is the most updated one? Is there a list of versions available as a docker container?

For example, I want to run PAGA and PAGA tree, but I would like to confirm that I have the newest version available.

Cheers,
Wendell

**Comment by rcannood** [comment]
Hello Wendell,

If you want to use the latest version, you should run `docker pull dynverse/ti_slingshot:latest` in the terminal and then use `create_ti_method_container("dynverse/ti_slingshot:latest")` in R.

dynmethods should always be using the latest stable version of each package. I should update dynmethods soon to reflect this, then you wouldn't encounter this issue anymore.

Kind regards,
Robrecht

**Comment by wendelljpereira** [comment]
Hi Robrecht,

Thank you very much for the information! 

Cheers,
Wendell
